version: '3'

services:

  letsencrypt:
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --standalone -d Wutterfly.com --text --agree-tos --server https://acme-v02.api.letsencrypt.org/directory --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
    environment:
      - TERM=xterm
