version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: on-failure
    volumes:
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx2.conf:/etc/nginx/nginx.conf:ro
      - ./src/:/www/data/:ro